[workspace]
members = [
    "intel-sgx/aesm-client",
    "intel-sgx/dcap-provider",
    "intel-sgx/dcap-ql-sys",
    "intel-sgx/dcap-ql",
    "intel-sgx/dcap-retrieve-pckid",
    "intel-sgx/enclave-runner",
    "intel-sgx/fortanix-sgx-abi",
    "intel-sgx/fortanix-sgx-tools",
    "ipc-queue",
    "intel-sgx/report-test",
    "rs-libc",
    "intel-sgx/sgxs",
    "intel-sgx/sgx-isa",
    "intel-sgx/sgx-pkix",
    "intel-sgx/sgxs-loaders",
    "intel-sgx/sgxs-tools"
]
exclude = ["examples"]
