[workspace]
members = [
    "fortanix-vme/fortanix-vme-abi",
    "fortanix-vme/fortanix-vme-runner",
    "fortanix-vme/tests/outgoing_connection",
    "intel-sgx/aesm-client",
    "intel-sgx/dcap-provider",
    "intel-sgx/dcap-ql-sys",
    "intel-sgx/dcap-ql",
    "intel-sgx/dcap-retrieve-pckid",
    "intel-sgx/enclave-runner",
    "intel-sgx/fortanix-sgx-abi",
    "intel-sgx/fortanix-sgx-tools",
    "intel-sgx/report-test",
    "intel-sgx/sgxs",
    "intel-sgx/sgx-isa",
    "intel-sgx/sgx-pkix",
    "intel-sgx/sgxs-loaders",
    "intel-sgx/sgxs-tools",
    "ipc-queue",
    "rs-libc",
]
exclude = ["examples"]

[patch.crates-io]
serde = { git = "https://github.com/fortanix/serde.git", branch = "master" }
vsock = { git = "https://github.com/raoulstrackx/vsock-rs.git", branch = "raoul/fortanixvme" }
