[package]
name = "fortanix-vme-runner"
version = "0.1.0"
edition = "2018"
authors = ["Fortanix, Inc."]

[dependencies]
fortanix-vme-abi = { path = "../fortanix-vme-abi" }
nix = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = { version = "0.11" }
vsock = "0.2.4"
