[package]
name = "nitro-attestation-verify"
version = "0.1.0"
authors = ["Adrian Cruceru <adrian.cruceru@fortanix.com>"]
edition = "2018"

[dependencies]
serde_cbor = {version = "0.11" }
aws-nitro-enclaves-cose = { git = "https://github.com/fortanix/aws-nitro-enclaves-cose.git", branch = "raoul/crypto_abstraction", default-features = false }
mbedtls8 = { git = "https://github.com/fortanix/rust-mbedtls", package = "mbedtls", branch = "acruceru/port-async-support", features = ["rdrand", "std", "async-rt", "dsa", "time"], default-features = false  }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
pkix = "0.1"

[dev-dependencies]
chrono = "0.4.0"
pkix = "0.1"
lazy_static = "1.3.0"
