[workspace]

[package]
name = "nitro-attestation-verify"
version = "0.1.0"
authors = ["Adrian Cruceru <adrian.cruceru@fortanix.com>"]
edition = "2018"

[dependencies]
serde_cbor = {version = "0.11" }
aws-nitro-enclaves-cose = { path = "../aws-nitro-enclaves-cose", default-features = false }
mbedtls8 = { git = "https://github.com/fortanix/rust-mbedtls", package = "mbedtls", branch = "acruceru/port-async-support", features = ["rdrand", "std", "async-rt", "dsa", "time"], optional = true, default-features = false  }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[dev-dependencies]
pkix = { path = "../../common/pkix" }
lazy_static = "1.3.0"

[features]
default = ["crypto_mbedtls"]
crypto_mbedtls = ["mbedtls8", "aws-nitro-enclaves-cose/crypto_mbedtls", "aws-nitro-enclaves-cose/key_mbedtls_pkey"]

migration_mode=["mbedtls8/migration_mode", "aws-nitro-enclaves-cose/migration_mode"]